server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    location /api/lastfm/ {
        # Указываем DNS-ресолверы, чтобы Nginx мог разрешить адрес Last.fm внутри контейнера
        resolver 8.8.8.8 1.1.1.1 valid=300s;
        resolver_timeout 5s;

        proxy_pass https://ws.audioscrobbler.com/2.0/;
        proxy_set_header Host ws.audioscrobbler.com;
        proxy_ssl_server_name on;
        proxy_ssl_session_reuse off;
        proxy_hide_header Access-Control-Allow-Origin;
    }
}
